/**
 * Gruvbox userstyles generator.
 *
 * Produces a single Stylus backup file (`dist/gruvbox-userstyles.import.json`)
 * that installs every upstream Catppuccin userstyle at once, recolored to
 * Gruvbox, WITHOUT editing the upstream style files. That keeps
 * `git merge upstream/main` clean.
 *
 * How it works:
 *   1. Assemble `lib/gruvbox-lib.less` from `lib/gruvbox-palette.less`
 *      (Gruvbox colors) + the upstream `lib/lib.less` filters/`#lib` API.
 *      This means whenever upstream changes the `#lib` API, regenerating
 *      automatically picks it up.
 *   2. For each style's `catppuccin.user.less`:
 *        - vendor the Gruvbox lib INLINE in place of the remote
 *          `@import "https://userstyles.catppuccin.com/lib/lib.less";`
 *          so the generated style is fully self-contained (no network needed
 *          by Stylus, and not dependent on this repo being pushed/reachable).
 *        - rewrite the visible metadata (name/namespace/urls/author/desc).
 *        - strip `@updateURL` so Stylus never auto-updates back to Catppuccin.
 *   3. Emit the Stylus import.json (schema mirrors upstream
 *      `scripts/stylus-import/main.ts`).
 *
 * Usage:  deno task generate:gruvbox
 */
import usercssMeta from "usercss-meta";
import { ensureDir } from "@std/fs";
import * as path from "@std/path";
import { REPO_ROOT } from "@/constants.ts";
import { getUserstylesFiles } from "@/utils.ts";
import { log } from "@/logger.ts";

// ---- Fork identity (edit these if you rename/move the repo) ---------------
const FORK = {
  owner: "BrigBryu",
  repo: "gruvbox-Userstyles",
  get slug() {
    return `${this.owner}/${this.repo}`;
  },
  get homepage() {
    return `https://github.com/${this.slug}`;
  },
};
const REMOTE_LIB_IMPORT =
  '@import "https://userstyles.catppuccin.com/lib/lib.less";';

// ---- 1. Build lib/gruvbox-lib.less ----------------------------------------
/**
 * Take the upstream lib.less, swap its `@catppuccin: { ... }` palette map for
 * the Gruvbox one, and keep everything else (filters + the `#lib` namespace).
 */
function buildGruvboxLib(): string {
  const upstream = Deno.readTextFileSync(
    path.join(REPO_ROOT, "lib", "lib.less"),
  );
  const gruvboxPalette = Deno.readTextFileSync(
    path.join(REPO_ROOT, "lib", "gruvbox-palette.less"),
  );

  // Extract just the `@catppuccin: { ... };` block from the Gruvbox source.
  const paletteMatch = gruvboxPalette.match(/@catppuccin:\s*\{[\s\S]*?\n\};/);
  if (!paletteMatch) {
    log.error("Could not find @catppuccin map in lib/gruvbox-palette.less");
    Deno.exit(1);
  }

  // Replace the upstream `@catppuccin: { ... };` map with the Gruvbox one.
  const replaced = upstream.replace(
    /@catppuccin:\s*\{[\s\S]*?\n\};/,
    () => paletteMatch[0],
  );
  if (replaced === upstream) {
    log.error("Could not find @catppuccin map in lib/lib.less");
    Deno.exit(1);
  }

  const header =
    "/* GENERATED by scripts/gruvbox/generate-import.ts — do not edit by hand.\n" +
    " * Source of colors: lib/gruvbox-palette.less\n" +
    " * Source of API:    lib/lib.less (upstream Catppuccin) */\n";
  return header + replaced;
}

// ---- 2. Rewrite a single style --------------------------------------------
function gruvboxifyStyle(content: string, gruvboxLib: string): string {
  // Split off the UserStyle metadata header so renames don't touch CSS body
  // (e.g. `#catppuccin(...)` mixin calls or `catppuccin.com` import URLs).
  const headerRe = /(\/\* ==UserStyle==)([\s\S]*?)(==\/UserStyle== \*\/)/;
  const m = content.match(headerRe);
  if (!m) {
    throw new Error("missing UserStyle metadata header");
  }

  let header = m[2];

  // @name "GitHub Catppuccin" -> "GitHub Gruvbox"
  header = header.replace(
    /^(@name\s+)(.*)$/m,
    (_all, p: string, val: string) =>
      p + val.replace(/Catppuccin/g, "Gruvbox"),
  );
  // namespace / homepageURL / supportURL all contain `catppuccin/userstyles`.
  header = header.replaceAll("catppuccin/userstyles", FORK.slug);
  // Fixed description + author (preserve Catppuccin attribution).
  header = header.replace(
    /^@description\s+.*$/m,
    "@description Unofficial Gruvbox theme based on Catppuccin userstyles",
  );
  header = header.replace(
    /^@author\s+.*$/m,
    `@author ${FORK.owner} (Gruvbox port) — based on Catppuccin (catppuccin/userstyles)`,
  );
  // Drop @updateURL so Stylus never silently pulls the Catppuccin version.
  header = header.replace(/^@updateURL\s+.*$\n?/m, "");

  let out = content.replace(headerRe, `$1${header}$3`);

  // Vendor the Gruvbox lib inline in place of the remote import.
  if (!out.includes(REMOTE_LIB_IMPORT)) {
    throw new Error("expected lib.less import not found");
  }
  out = out.replace(
    REMOTE_LIB_IMPORT,
    () =>
      `/* Gruvbox: vendored lib (was ${REMOTE_LIB_IMPORT}) */\n${gruvboxLib}`,
  );

  return out;
}

// ---- 3. Generate -----------------------------------------------------------
// Recommended Stylus settings. updateInterval 0 => never auto-check.
const settings = {
  settings: {
    updateInterval: 0,
    updateOnlyEnabled: true,
    patchCsp: true,
    "editor.linter": "",
  },
};

const gruvboxLib = buildGruvboxLib();
await Deno.writeTextFile(
  path.join(REPO_ROOT, "lib", "gruvbox-lib.less"),
  gruvboxLib,
);

const data: Record<string, unknown>[] = [settings];
let count = 0;

for (const file of getUserstylesFiles()) {
  const original = await Deno.readTextFile(file);
  let source: string;
  try {
    source = gruvboxifyStyle(original, gruvboxLib);
  } catch (err) {
    log.error(`Skipping ${path.relative(REPO_ROOT, file)}: ${err.message}`);
    continue;
  }

  const { metadata } = usercssMeta.parse(source);

  data.push({
    enabled: true,
    name: metadata.name,
    description: metadata.description,
    author: metadata.author,
    url: FORK.homepage,
    // Explicitly null so Stylus shows no update source for these styles.
    updateUrl: null,
    usercssData: metadata,
    sourceCode: source,
  });
  count++;
}

await ensureDir(path.join(REPO_ROOT, "dist"));
const outPath = path.join(REPO_ROOT, "dist", "gruvbox-userstyles.import.json");
await Deno.writeTextFile(outPath, JSON.stringify(data));

console.log(
  `Generated ${count} Gruvbox styles -> ${
    path.relative(REPO_ROOT, outPath)
  }`,
);
console.log(`Also wrote lib/gruvbox-lib.less`);
